// Mock数据 - SQL转API列表
import type { ApiDefinition } from './types';

export const mockApiList: ApiDefinition[] = [
  {
    id: 'api_sql_001',
    name: '查询用户列表',
    description: '根据状态查询用户信息',
    sqlStatement: 'SELECT * FROM users WHERE status = ${status} ORDER BY create_time DESC',
    databaseType: 'MySQL',
    httpMethod: 'GET',
    apiUrl: '/api/v1/users/query',
    parameters: [
      {
        name: 'status',
        type: 'string',
        required: true,
        defaultValue: 'active',
        description: '用户状态: active/inactive',
        location: 'query',
      },
    ],
    securityLevel: 'low',
    status: 'active',
    creator: 'zhangsan',
    createdAt: '2026-05-20 10:30:00',
    updatedAt: '2026-05-22 14:20:00',
  },
  {
    id: 'api_sql_002',
    name: '创建订单',
    description: '新增订单记录',
    sqlStatement: 'INSERT INTO orders (user_id, product_id, amount) VALUES (${userId}, ${productId}, ${amount})',
    databaseType: 'MySQL',
    httpMethod: 'POST',
    apiUrl: '/api/v1/orders/create',
    parameters: [
      {
        name: 'userId',
        type: 'number',
        required: true,
        description: '用户ID',
        location: 'body',
      },
      {
        name: 'productId',
        type: 'number',
        required: true,
        description: '产品ID',
        location: 'body',
      },
      {
        name: 'amount',
        type: 'number',
        required: true,
        description: '订单金额',
        location: 'body',
      },
    ],
    securityLevel: 'high',
    status: 'active',
    creator: 'lisi',
    createdAt: '2026-05-21 09:15:00',
    updatedAt: '2026-05-22 11:30:00',
  },
  {
    id: 'api_sql_003',
    name: '查询商品详情',
    description: '根据商品ID查询详细信息',
    sqlStatement: 'SELECT p.*, c.name as category_name FROM products p LEFT JOIN categories c ON p.category_id = c.id WHERE p.id = ${id}',
    databaseType: 'MySQL',
    httpMethod: 'GET',
    apiUrl: '/api/v1/products/detail',
    parameters: [
      {
        name: 'id',
        type: 'number',
        required: true,
        description: '商品ID',
        location: 'query',
      },
    ],
    securityLevel: 'medium',
    status: 'draft',
    creator: 'wangwu',
    createdAt: '2026-05-22 08:00:00',
    updatedAt: '2026-05-22 08:00:00',
  },
  {
    id: 'api_sql_004',
    name: '更新用户信息',
    description: '更新用户基本信息',
    sqlStatement: 'UPDATE users SET name = ${name}, email = ${email} WHERE id = ${userId}',
    databaseType: 'MySQL',
    httpMethod: 'POST',
    apiUrl: '/api/v1/users/update',
    parameters: [
      {
        name: 'userId',
        type: 'number',
        required: true,
        description: '用户ID',
        location: 'body',
      },
      {
        name: 'name',
        type: 'string',
        required: true,
        description: '用户姓名',
        location: 'body',
      },
      {
        name: 'email',
        type: 'string',
        required: false,
        description: '用户邮箱',
        location: 'body',
      },
    ],
    securityLevel: 'high',
    status: 'pending_approval',
    creator: 'zhangsan',
    createdAt: '2026-05-22 10:00:00',
    updatedAt: '2026-05-22 10:00:00',
  },
  {
    id: 'api_sql_005',
    name: '统计订单数量',
    description: '按状态统计订单数量',
    sqlStatement: 'SELECT status, COUNT(*) as count FROM orders GROUP BY status',
    databaseType: 'MySQL',
    httpMethod: 'GET',
    apiUrl: '/api/v1/orders/statistics',
    parameters: [],
    securityLevel: 'low',
    status: 'deprecated',
    creator: 'lisi',
    createdAt: '2026-05-15 14:30:00',
    updatedAt: '2026-05-20 16:45:00',
  },
];
